[build]
  command = "npm run build"  # Replace this with your actual build command
  publish = "build"         # Replace this with the directory where your build artifacts are generated

[[redirects]]
  from = "/*"
  to = "/huddle.html"
  status = 200
